＃用于部署静态内容到github页面的简单工作流程
名称：将静态内容部署到页面

在：
  ＃在针对默认分支的推动下运行
  推：
    分支：[ “ Main” ]

  ＃允许您从“动作”选项卡手动运行此工作流程
  workflow_dispatch ：

＃设置github_token的权限，以允许部署到github页面
许可：
  内容：阅读
  页面：写
  id-token ：写

＃仅允许一个并发部署，跳过运行在运行内和最新排队之间排队。
＃但是，不要取消过程中的运行，因为我们希望允许这些生产部署完成。
并发：
  小组：“页面”
  取消过程：false

工作：
  ＃单部部署工作，因为我们只是部署
  部署：
    环境：
      名称： github页面
      URL ： $ { { steps.deployment.outputs.page_url } }}
    运行： ubuntu-latest
    步骤：
      -名称：结帐
        用途： Action/Checkout@V4
      -名称：设置页面
        用途： Action/Configure页面@V5
      -名称：上传工件
        用途：操作/上传页面-Artifact@v3
        和：
          ＃上传整个存储库
          小路：'。'
      -名称：部署到github页面
        ID ：部署
        用途：操作/部署页面@v4
